/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ihm.java
 *
 * Created on 18 nov. 2010, 10:53:51
 */
package courseRelais.ihm;

import courseRelais.ctrl.ItfCtrlIhm;
import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author waeberla
 */
public class Ihm extends javax.swing.JFrame implements ItfIhmCtrl {

    /** Creates new form Ihm */
    public Ihm() {
        initComponents();
        model = new DefaultListModel();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        panelEquipe3 = new javax.swing.JPanel();
        lCoureur3_1 = new javax.swing.JLabel();
        pbCoureur3_1 = new javax.swing.JProgressBar();
        lCoureur3_2 = new javax.swing.JLabel();
        pbCoureur3_2 = new javax.swing.JProgressBar();
        pbCoureur3_3 = new javax.swing.JProgressBar();
        pbCoureur3_4 = new javax.swing.JProgressBar();
        lCoureur3_3 = new javax.swing.JLabel();
        lCoureur3_4 = new javax.swing.JLabel();
        lEquipe3 = new javax.swing.JLabel();
        panelEquipe2 = new javax.swing.JPanel();
        lCoureur2_1 = new javax.swing.JLabel();
        pbCoureur2_1 = new javax.swing.JProgressBar();
        lCoureur2_2 = new javax.swing.JLabel();
        pbCoureur2_2 = new javax.swing.JProgressBar();
        pbCoureur2_3 = new javax.swing.JProgressBar();
        pbCoureur2_4 = new javax.swing.JProgressBar();
        lCoureur2_3 = new javax.swing.JLabel();
        lCoureur2_4 = new javax.swing.JLabel();
        lEquipe2 = new javax.swing.JLabel();
        tHorloge = new javax.swing.JTextField();
        tChrono = new javax.swing.JTextField();
        bStart = new javax.swing.JButton();
        bPause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste = new javax.swing.JList();
        lTitreListe = new javax.swing.JLabel();
        bDemarreThreads = new javax.swing.JButton();
        bDetruitThreads = new javax.swing.JButton();
        panelEquipe1 = new javax.swing.JPanel();
        lEquipe1 = new javax.swing.JLabel();
        lCoureur1_1 = new javax.swing.JLabel();
        pbCoureur1_1 = new javax.swing.JProgressBar();
        lCoureur1_2 = new javax.swing.JLabel();
        pbCoureur1_2 = new javax.swing.JProgressBar();
        pbCoureur1_3 = new javax.swing.JProgressBar();
        pbCoureur1_4 = new javax.swing.JProgressBar();
        lCoureur1_3 = new javax.swing.JLabel();
        lCoureur1_4 = new javax.swing.JLabel();
        panelEquipe4 = new javax.swing.JPanel();
        lCoureur4_1 = new javax.swing.JLabel();
        pbCoureur4_1 = new javax.swing.JProgressBar();
        lCoureur4_2 = new javax.swing.JLabel();
        pbCoureur4_2 = new javax.swing.JProgressBar();
        pbCoureur4_3 = new javax.swing.JProgressBar();
        pbCoureur4_4 = new javax.swing.JProgressBar();
        lCoureur4_3 = new javax.swing.JLabel();
        lCoureur4_4 = new javax.swing.JLabel();
        lEquipe4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course relais du 4 X 100 m");
        setResizable(false);

        panelEquipe3.setBackground(new java.awt.Color(204, 255, 204));

        lCoureur3_1.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur3_1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur3_1.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur3_1.setText("Coureur 1");

        pbCoureur3_1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur3_1.setForeground(new java.awt.Color(102, 255, 0));
        pbCoureur3_1.setToolTipText("Coureur 1");
        pbCoureur3_1.setBorderPainted(false);
        pbCoureur3_1.setName("coureur 1"); // NOI18N
        pbCoureur3_1.setOpaque(true);
        pbCoureur3_1.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur3_1.setRequestFocusEnabled(false);
        pbCoureur3_1.setString("0 mètre"); // NOI18N
        pbCoureur3_1.setStringPainted(true);

        lCoureur3_2.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur3_2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur3_2.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur3_2.setText("Coureur 2");

        pbCoureur3_2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur3_2.setForeground(new java.awt.Color(102, 255, 0));
        pbCoureur3_2.setToolTipText("Coureur 1");
        pbCoureur3_2.setBorderPainted(false);
        pbCoureur3_2.setName("coureur 1"); // NOI18N
        pbCoureur3_2.setOpaque(true);
        pbCoureur3_2.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur3_2.setRequestFocusEnabled(false);
        pbCoureur3_2.setString("0 mètre"); // NOI18N
        pbCoureur3_2.setStringPainted(true);

        pbCoureur3_3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur3_3.setForeground(new java.awt.Color(102, 255, 0));
        pbCoureur3_3.setToolTipText("Coureur 1");
        pbCoureur3_3.setBorderPainted(false);
        pbCoureur3_3.setName("coureur 1"); // NOI18N
        pbCoureur3_3.setOpaque(true);
        pbCoureur3_3.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur3_3.setRequestFocusEnabled(false);
        pbCoureur3_3.setString("0 mètre"); // NOI18N
        pbCoureur3_3.setStringPainted(true);

        pbCoureur3_4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur3_4.setForeground(new java.awt.Color(102, 255, 0));
        pbCoureur3_4.setToolTipText("Coureur 1");
        pbCoureur3_4.setBorderPainted(false);
        pbCoureur3_4.setName("coureur 1"); // NOI18N
        pbCoureur3_4.setOpaque(true);
        pbCoureur3_4.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur3_4.setRequestFocusEnabled(false);
        pbCoureur3_4.setString("0 mètre"); // NOI18N
        pbCoureur3_4.setStringPainted(true);

        lCoureur3_3.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur3_3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur3_3.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur3_3.setText("Coureur 3");

        lCoureur3_4.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur3_4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur3_4.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur3_4.setText("Coureur 4");

        lEquipe3.setBackground(new java.awt.Color(204, 255, 204));
        lEquipe3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lEquipe3.setForeground(new java.awt.Color(0, 0, 204));
        lEquipe3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipe3.setText("Equipe No 3");

        javax.swing.GroupLayout panelEquipe3Layout = new javax.swing.GroupLayout(panelEquipe3);
        panelEquipe3.setLayout(panelEquipe3Layout);
        panelEquipe3Layout.setHorizontalGroup(
            panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEquipe3, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addGroup(panelEquipe3Layout.createSequentialGroup()
                        .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lCoureur3_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur3_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur3_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur3_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur3_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelEquipe3Layout.setVerticalGroup(
            panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe3Layout.createSequentialGroup()
                .addComponent(lEquipe3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCoureur3_1)
                    .addComponent(lCoureur3_2)
                    .addComponent(lCoureur3_3)
                    .addComponent(lCoureur3_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbCoureur3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        panelEquipe2.setBackground(new java.awt.Color(255, 255, 204));

        lCoureur2_1.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur2_1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur2_1.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur2_1.setText("Coureur 1");

        pbCoureur2_1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur2_1.setForeground(new java.awt.Color(255, 255, 0));
        pbCoureur2_1.setToolTipText("Coureur 1");
        pbCoureur2_1.setBorderPainted(false);
        pbCoureur2_1.setName("coureur 1"); // NOI18N
        pbCoureur2_1.setOpaque(true);
        pbCoureur2_1.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur2_1.setRequestFocusEnabled(false);
        pbCoureur2_1.setString("0 mètre"); // NOI18N
        pbCoureur2_1.setStringPainted(true);

        lCoureur2_2.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur2_2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur2_2.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur2_2.setText("Coureur 2");

        pbCoureur2_2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur2_2.setForeground(new java.awt.Color(255, 255, 0));
        pbCoureur2_2.setToolTipText("Coureur 1");
        pbCoureur2_2.setBorderPainted(false);
        pbCoureur2_2.setName("coureur 1"); // NOI18N
        pbCoureur2_2.setOpaque(true);
        pbCoureur2_2.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur2_2.setRequestFocusEnabled(false);
        pbCoureur2_2.setString("0 mètre"); // NOI18N
        pbCoureur2_2.setStringPainted(true);

        pbCoureur2_3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur2_3.setForeground(new java.awt.Color(255, 255, 0));
        pbCoureur2_3.setToolTipText("Coureur 1");
        pbCoureur2_3.setBorderPainted(false);
        pbCoureur2_3.setName("coureur 1"); // NOI18N
        pbCoureur2_3.setOpaque(true);
        pbCoureur2_3.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur2_3.setRequestFocusEnabled(false);
        pbCoureur2_3.setString("0 mètre"); // NOI18N
        pbCoureur2_3.setStringPainted(true);

        pbCoureur2_4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur2_4.setForeground(new java.awt.Color(255, 255, 0));
        pbCoureur2_4.setToolTipText("Coureur 1");
        pbCoureur2_4.setBorderPainted(false);
        pbCoureur2_4.setName("coureur 1"); // NOI18N
        pbCoureur2_4.setOpaque(true);
        pbCoureur2_4.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur2_4.setRequestFocusEnabled(false);
        pbCoureur2_4.setString("0 mètre"); // NOI18N
        pbCoureur2_4.setStringPainted(true);

        lCoureur2_3.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur2_3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur2_3.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur2_3.setText("Coureur 3");

        lCoureur2_4.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur2_4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur2_4.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur2_4.setText("Coureur 4");

        lEquipe2.setBackground(new java.awt.Color(204, 255, 204));
        lEquipe2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lEquipe2.setForeground(new java.awt.Color(0, 0, 204));
        lEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipe2.setText("Equipe No 2");

        javax.swing.GroupLayout panelEquipe2Layout = new javax.swing.GroupLayout(panelEquipe2);
        panelEquipe2.setLayout(panelEquipe2Layout);
        panelEquipe2Layout.setHorizontalGroup(
            panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEquipe2, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addGroup(panelEquipe2Layout.createSequentialGroup()
                        .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lCoureur2_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur2_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur2_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelEquipe2Layout.setVerticalGroup(
            panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe2Layout.createSequentialGroup()
                .addComponent(lEquipe2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCoureur2_1)
                    .addComponent(lCoureur2_2)
                    .addComponent(lCoureur2_3)
                    .addComponent(lCoureur2_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbCoureur2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tHorloge.setBackground(new java.awt.Color(255, 255, 204));
        tHorloge.setEditable(false);
        tHorloge.setFont(new java.awt.Font("Verdana", 1, 36));
        tHorloge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tHorloge.setText("Horloge");

        tChrono.setBackground(new java.awt.Color(255, 204, 204));
        tChrono.setEditable(false);
        tChrono.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        tChrono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tChrono.setText("Chrono OFF");

        bStart.setBackground(new java.awt.Color(102, 255, 51));
        bStart.setFont(new java.awt.Font("Verdana", 1, 36));
        bStart.setText("Start de la course");
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        bPause.setBackground(new java.awt.Color(255, 204, 102));
        bPause.setFont(new java.awt.Font("Verdana", 1, 36));
        bPause.setText("Pause de la course");
        bPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPauseActionPerformed(evt);
            }
        });

        liste.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        liste.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(liste);

        lTitreListe.setFont(new java.awt.Font("Verdana", 1, 14));
        lTitreListe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitreListe.setText("Information sur la course");

        bDemarreThreads.setFont(new java.awt.Font("Verdana", 1, 14));
        bDemarreThreads.setText("Démarre les threads de l'application");
        bDemarreThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDemarreThreadsActionPerformed(evt);
            }
        });

        bDetruitThreads.setFont(new java.awt.Font("Verdana", 1, 14));
        bDetruitThreads.setText("Détruit les threads de l'application");
        bDetruitThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetruitThreadsActionPerformed(evt);
            }
        });

        panelEquipe1.setBackground(new java.awt.Color(204, 255, 255));

        lEquipe1.setBackground(new java.awt.Color(204, 255, 204));
        lEquipe1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lEquipe1.setForeground(new java.awt.Color(0, 0, 204));
        lEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipe1.setText("Equipe No 1");

        lCoureur1_1.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur1_1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur1_1.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur1_1.setText("Coureur 1");

        pbCoureur1_1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur1_1.setForeground(new java.awt.Color(0, 255, 255));
        pbCoureur1_1.setToolTipText("Coureur 1");
        pbCoureur1_1.setBorderPainted(false);
        pbCoureur1_1.setName("coureur 1"); // NOI18N
        pbCoureur1_1.setOpaque(true);
        pbCoureur1_1.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur1_1.setRequestFocusEnabled(false);
        pbCoureur1_1.setString("0 mètre"); // NOI18N
        pbCoureur1_1.setStringPainted(true);

        lCoureur1_2.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur1_2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur1_2.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur1_2.setText("Coureur 2");

        pbCoureur1_2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur1_2.setForeground(new java.awt.Color(0, 255, 255));
        pbCoureur1_2.setToolTipText("Coureur 1");
        pbCoureur1_2.setBorderPainted(false);
        pbCoureur1_2.setName("coureur 1"); // NOI18N
        pbCoureur1_2.setOpaque(true);
        pbCoureur1_2.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur1_2.setRequestFocusEnabled(false);
        pbCoureur1_2.setString("0 mètre"); // NOI18N
        pbCoureur1_2.setStringPainted(true);

        pbCoureur1_3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur1_3.setForeground(new java.awt.Color(0, 255, 255));
        pbCoureur1_3.setToolTipText("Coureur 1");
        pbCoureur1_3.setBorderPainted(false);
        pbCoureur1_3.setName("coureur 1"); // NOI18N
        pbCoureur1_3.setOpaque(true);
        pbCoureur1_3.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur1_3.setRequestFocusEnabled(false);
        pbCoureur1_3.setString("0 mètre"); // NOI18N
        pbCoureur1_3.setStringPainted(true);

        pbCoureur1_4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur1_4.setForeground(new java.awt.Color(0, 255, 255));
        pbCoureur1_4.setToolTipText("Coureur 1");
        pbCoureur1_4.setBorderPainted(false);
        pbCoureur1_4.setName("coureur 1"); // NOI18N
        pbCoureur1_4.setOpaque(true);
        pbCoureur1_4.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur1_4.setRequestFocusEnabled(false);
        pbCoureur1_4.setString("0 mètre"); // NOI18N
        pbCoureur1_4.setStringPainted(true);

        lCoureur1_3.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur1_3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur1_3.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur1_3.setText("Coureur 3");

        lCoureur1_4.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur1_4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur1_4.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur1_4.setText("Coureur 4");

        javax.swing.GroupLayout panelEquipe1Layout = new javax.swing.GroupLayout(panelEquipe1);
        panelEquipe1.setLayout(panelEquipe1Layout);
        panelEquipe1Layout.setHorizontalGroup(
            panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEquipe1, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
                    .addGroup(panelEquipe1Layout.createSequentialGroup()
                        .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lCoureur1_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur1_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEquipe1Layout.setVerticalGroup(
            panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe1Layout.createSequentialGroup()
                .addComponent(lEquipe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCoureur1_1)
                    .addComponent(lCoureur1_2)
                    .addComponent(lCoureur1_3)
                    .addComponent(lCoureur1_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbCoureur1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelEquipe4.setBackground(new java.awt.Color(255, 204, 255));

        lCoureur4_1.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur4_1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur4_1.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur4_1.setText("Coureur 1");

        pbCoureur4_1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur4_1.setForeground(new java.awt.Color(255, 51, 255));
        pbCoureur4_1.setToolTipText("Coureur 1");
        pbCoureur4_1.setBorderPainted(false);
        pbCoureur4_1.setName("coureur 1"); // NOI18N
        pbCoureur4_1.setOpaque(true);
        pbCoureur4_1.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur4_1.setRequestFocusEnabled(false);
        pbCoureur4_1.setString("0 mètre"); // NOI18N
        pbCoureur4_1.setStringPainted(true);

        lCoureur4_2.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur4_2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur4_2.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur4_2.setText("Coureur 2");

        pbCoureur4_2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur4_2.setForeground(new java.awt.Color(255, 51, 255));
        pbCoureur4_2.setToolTipText("Coureur 1");
        pbCoureur4_2.setBorderPainted(false);
        pbCoureur4_2.setName("coureur 1"); // NOI18N
        pbCoureur4_2.setOpaque(true);
        pbCoureur4_2.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur4_2.setRequestFocusEnabled(false);
        pbCoureur4_2.setString("0 mètre"); // NOI18N
        pbCoureur4_2.setStringPainted(true);

        pbCoureur4_3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur4_3.setForeground(new java.awt.Color(255, 51, 255));
        pbCoureur4_3.setToolTipText("Coureur 1");
        pbCoureur4_3.setBorderPainted(false);
        pbCoureur4_3.setName("coureur 1"); // NOI18N
        pbCoureur4_3.setOpaque(true);
        pbCoureur4_3.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur4_3.setRequestFocusEnabled(false);
        pbCoureur4_3.setString("0 mètre"); // NOI18N
        pbCoureur4_3.setStringPainted(true);

        pbCoureur4_4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pbCoureur4_4.setForeground(new java.awt.Color(255, 51, 255));
        pbCoureur4_4.setToolTipText("Coureur 1");
        pbCoureur4_4.setBorderPainted(false);
        pbCoureur4_4.setName("coureur 1"); // NOI18N
        pbCoureur4_4.setOpaque(true);
        pbCoureur4_4.setPreferredSize(new java.awt.Dimension(10, 20));
        pbCoureur4_4.setRequestFocusEnabled(false);
        pbCoureur4_4.setString("0 mètre"); // NOI18N
        pbCoureur4_4.setStringPainted(true);

        lCoureur4_3.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur4_3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur4_3.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur4_3.setText("Coureur 3");

        lCoureur4_4.setBackground(new java.awt.Color(204, 255, 204));
        lCoureur4_4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lCoureur4_4.setForeground(new java.awt.Color(0, 0, 204));
        lCoureur4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCoureur4_4.setText("Coureur 4");

        lEquipe4.setBackground(new java.awt.Color(204, 255, 204));
        lEquipe4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lEquipe4.setForeground(new java.awt.Color(0, 0, 204));
        lEquipe4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEquipe4.setText("Equipe No 4");

        javax.swing.GroupLayout panelEquipe4Layout = new javax.swing.GroupLayout(panelEquipe4);
        panelEquipe4.setLayout(panelEquipe4Layout);
        panelEquipe4Layout.setHorizontalGroup(
            panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEquipe4, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addGroup(panelEquipe4Layout.createSequentialGroup()
                        .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lCoureur4_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur4_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur4_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur4_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lCoureur4_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbCoureur4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelEquipe4Layout.setVerticalGroup(
            panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipe4Layout.createSequentialGroup()
                .addComponent(lEquipe4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCoureur4_1)
                    .addComponent(lCoureur4_2)
                    .addComponent(lCoureur4_3)
                    .addComponent(lCoureur4_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEquipe4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbCoureur4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbCoureur4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelEquipe1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createSequentialGroup()
                            .addComponent(tHorloge, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tChrono)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelEquipe4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEquipe3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEquipe2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addComponent(bDemarreThreads)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDetruitThreads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bStart, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTitreListe, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))))
                .addGap(150, 150, 150))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tHorloge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tChrono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bStart)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(lTitreListe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(bPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bDemarreThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bDetruitThreads, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                            .addGroup(panelGeneralLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        initIhmCourse();
        refCtrl.demarreCourse();
    }//GEN-LAST:event_bStartActionPerformed

    private void bPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPauseActionPerformed
        refCtrl.pauseCourse();
    }//GEN-LAST:event_bPauseActionPerformed

    private void bDemarreThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDemarreThreadsActionPerformed
        refCtrl.demarreThreads();
    }//GEN-LAST:event_bDemarreThreadsActionPerformed

    private void bDetruitThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetruitThreadsActionPerformed
        refCtrl.detruitThreads();
    }//GEN-LAST:event_bDetruitThreadsActionPerformed

    // Implémentation des méthodes de ItfIhmCtrl
    public void afficheDateCourante(String laDateCourante) {
        tHorloge.setText(laDateCourante);
    }

    public void afficheTempsChrono(String temps) {
        tChrono.setText(temps);
    }

    public void initIhmCourse(){
            pbCoureur1_1.setValue(0);
            pbCoureur1_2.setValue(0);
            pbCoureur1_3.setValue(0);
            pbCoureur1_4.setValue(0);
            pbCoureur2_1.setValue(0);
            pbCoureur2_2.setValue(0);
            pbCoureur2_3.setValue(0);
            pbCoureur2_4.setValue(0);
            pbCoureur3_1.setValue(0);
            pbCoureur3_2.setValue(0);
            pbCoureur3_3.setValue(0);
            pbCoureur3_4.setValue(0);
            pbCoureur4_1.setValue(0);
            pbCoureur4_2.setValue(0);
            pbCoureur4_3.setValue(0);
            pbCoureur4_4.setValue(0);
            pbCoureur1_1.setString("0 mètre");
            pbCoureur1_2.setString("0 mètre");
            pbCoureur1_3.setString("0 mètre");
            pbCoureur1_4.setString("0 mètre");
            pbCoureur2_1.setString("0 mètre");
            pbCoureur2_2.setString("0 mètre");
            pbCoureur2_3.setString("0 mètre");
            pbCoureur2_4.setString("0 mètre");
            pbCoureur3_1.setString("0 mètre");
            pbCoureur3_2.setString("0 mètre");
            pbCoureur3_3.setString("0 mètre");
            pbCoureur3_4.setString("0 mètre");
            pbCoureur4_1.setString("0 mètre");
            pbCoureur4_2.setString("0 mètre");
            pbCoureur4_3.setString("0 mètre");
            pbCoureur4_4.setString("0 mètre");
            lCoureur1_1.setText("Coureur 1");
            lCoureur2_1.setText("Coureur 1");
            lCoureur3_1.setText("Coureur 1");
            lCoureur4_1.setText("Coureur 1");
            lCoureur1_2.setText("Coureur 2");
            lCoureur2_2.setText("Coureur 2");
            lCoureur3_2.setText("Coureur 2");
            lCoureur4_2.setText("Coureur 2");
            lCoureur1_3.setText("Coureur 3");
            lCoureur2_3.setText("Coureur 3");
            lCoureur3_3.setText("Coureur 3");
            lCoureur4_3.setText("Coureur 3");
            lCoureur1_4.setText("Coureur 4");
            lCoureur2_4.setText("Coureur 4");
            lCoureur3_4.setText("Coureur 4");
            lCoureur4_4.setText("Coureur 4");
            lEquipe1.setText("Equipe 1");
            lEquipe2.setText("Equipe 2");
            lEquipe3.setText("Equipe 3");
            lEquipe4.setText("Equipe 4");
    }
    public void toggleBoutonStart(boolean on) {
        if (on) {
            bStart.setBackground(Color.green);
        } else {
            bStart.setBackground(Color.red);
        }
        bStart.setEnabled(on);
    }

    public void afficheDistance(int equipe, int coureur, int distance) {
        switch (equipe) {
            case 1:
                switch (coureur) {
                    case 1:
                        pbCoureur1_1.setValue(distance);
                        pbCoureur1_1.setString(distance + " mètres");
                        break;
                    case 2:
                        pbCoureur1_2.setValue(distance);
                        pbCoureur1_2.setString(distance + " mètres");
                        break;
                    case 3:
                        pbCoureur1_3.setValue(distance);
                        pbCoureur1_3.setString(distance + " mètres");
                        break;
                    case 4:
                        pbCoureur1_4.setValue(distance);
                        pbCoureur1_4.setString(distance + " mètres");
                        break;
                }
                break;
            case 2:
                switch (coureur) {
                    case 1:
                        pbCoureur2_1.setValue(distance);
                        pbCoureur2_1.setString(distance + " mètres");
                        break;
                    case 2:
                        pbCoureur2_2.setValue(distance);
                        pbCoureur2_2.setString(distance + " mètres");
                        break;
                    case 3:
                        pbCoureur2_3.setValue(distance);
                        pbCoureur2_3.setString(distance + " mètres");
                        break;
                    case 4:
                        pbCoureur2_4.setValue(distance);
                        pbCoureur2_4.setString(distance + " mètres");
                        break;
                }
                break;
            case 3:
                switch (coureur) {
                    case 1:
                        pbCoureur3_1.setValue(distance);
                        pbCoureur3_1.setString(distance + " mètres");
                        break;
                    case 2:
                        pbCoureur3_2.setValue(distance);
                        pbCoureur3_2.setString(distance + " mètres");
                        break;
                    case 3:
                        pbCoureur3_3.setValue(distance);
                        pbCoureur3_3.setString(distance + " mètres");
                        break;
                    case 4:
                        pbCoureur3_4.setValue(distance);
                        pbCoureur3_4.setString(distance + " mètres");
                        break;
                }
                break;
            case 4:
                switch (coureur) {
                    case 1:
                        pbCoureur4_1.setValue(distance);
                        pbCoureur4_1.setString(distance + " mètres");
                        break;
                    case 2:
                        pbCoureur4_2.setValue(distance);
                        pbCoureur4_2.setString(distance + " mètres");
                        break;
                    case 3:
                        pbCoureur4_3.setValue(distance);
                        pbCoureur4_3.setString(distance + " mètres");
                        break;
                    case 4:
                        pbCoureur4_4.setValue(distance);
                        pbCoureur4_4.setString(distance + " mètres");
                        break;
                }
                break;

        }
    }

    public void afficheFinCourseEquipe(int equipe, String info) {
        switch (equipe) {
            case 1:
                lEquipe1.setText("Equipe 1 arrivé " + info);
                break;
            case 2:
                lEquipe2.setText("Equipe 2 arrivé " + info);
                break;
            case 3:
                lEquipe3.setText("Equipe 3 arrivé " + info);
                break;
            case 4:
                lEquipe4.setText("Equipe 4 arrivé " + info);
                break;
        }
    }

    public void afficheFinCourseCoureur(int equipe, int coureur, String info) {
        switch (equipe) {
            case 1:
                switch (coureur) {
                    case 1:
                        lEquipe1.setText("Coureur 1 arrivé " + info);
                        lCoureur1_1.setText("Coureur 1 arrivé " + info);
                        break;
                    case 2:
                        lEquipe1.setText("Coureur 2 arrivé " + info);
                        lCoureur1_2.setText("Coureur 2 arrivé " + info);
                        break;
                    case 3:
                        lEquipe1.setText("Coureur 3 arrivé " + info);
                        lCoureur1_3.setText("Coureur 3 arrivé " + info);
                        break;
                    case 4:
                        lEquipe1.setText("Coureur 4 arrivé " + info);
                        lCoureur1_4.setText("Coureur 4 arrivé " + info);
                        break;
                }
                break;
            case 2:
                switch (coureur) {
                    case 1:
                        lEquipe2.setText("Coureur 1 arrivé " + info);
                        lCoureur2_1.setText("Coureur 1 arrivé " + info);
                        break;
                    case 2:
                        lEquipe2.setText("Coureur 2 arrivé " + info);
                        lCoureur2_2.setText("Coureur 2 arrivé " + info);
                        break;
                    case 3:
                        lEquipe2.setText("Coureur 3 arrivé " + info);
                        lCoureur2_3.setText("Coureur 3 arrivé " + info);
                        break;
                    case 4:
                        lEquipe2.setText("Coureur 4 arrivé " + info);
                        lCoureur2_4.setText("Coureur 4 arrivé " + info);
                        break;
                }
                break;
            case 3:
                switch (coureur) {
                    case 1:
                        lEquipe3.setText("Coureur 1 arrivé " + info);
                        lCoureur3_1.setText("Coureur 1 arrivé " + info);
                        break;
                    case 2:
                        lEquipe3.setText("Coureur 2 arrivé " + info);
                        lCoureur3_2.setText("Coureur 2 arrivé " + info);
                        break;
                    case 3:
                        lEquipe3.setText("Coureur 3 arrivé " + info);
                        lCoureur3_3.setText("Coureur 3 arrivé " + info);
                        break;
                    case 4:
                        lEquipe3.setText("Coureur 4 arrivé " + info);
                        lCoureur3_4.setText("Coureur 4 arrivé " + info);
                        break;
                }
                break;
            case 4:
                switch (coureur) {
                    case 1:
                        lEquipe4.setText("Coureur 1 arrivé " + info);
                        lCoureur4_1.setText("Coureur 1 arrivé " + info);
                        break;
                    case 2:
                        lEquipe4.setText("Coureur 2 arrivé " + info);
                        lCoureur4_2.setText("Coureur 2 arrivé " + info);
                        break;
                    case 3:
                        lEquipe4.setText("Coureur 3 arrivé " + info);
                        lCoureur4_3.setText("Coureur 3 arrivé " + info);
                        break;
                    case 4:
                        lEquipe4.setText("Coureur 4 arrivé " + info);
                        lCoureur4_4.setText("Coureur 4 arrivé " + info);
                        break;
                }
                break;
        }

    }

    public void afficheFinCourse() {
        toggleBoutonStart(false);
    }

    public void afficheInfo(String info) {
        if (info != null) {
            model.addElement(info);
        }
        liste.setModel(model);
    }

    public void initialiseTextCoureur() {
        lEquipe1.setText("Equipe No 1");
        lEquipe2.setText("Equipe No 2");
        lEquipe3.setText("Equipe No 3");
        lEquipe4.setText("Equipe No 4");
    }

    public ItfCtrlIhm getRefCtrl() {
        return refCtrl;
    }

    public void setRefCtrl(ItfCtrlIhm refCtrl) {
        this.refCtrl = refCtrl;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDemarreThreads;
    private javax.swing.JButton bDetruitThreads;
    private javax.swing.JButton bPause;
    private javax.swing.JButton bStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCoureur1_1;
    private javax.swing.JLabel lCoureur1_2;
    private javax.swing.JLabel lCoureur1_3;
    private javax.swing.JLabel lCoureur1_4;
    private javax.swing.JLabel lCoureur2_1;
    private javax.swing.JLabel lCoureur2_2;
    private javax.swing.JLabel lCoureur2_3;
    private javax.swing.JLabel lCoureur2_4;
    private javax.swing.JLabel lCoureur3_1;
    private javax.swing.JLabel lCoureur3_2;
    private javax.swing.JLabel lCoureur3_3;
    private javax.swing.JLabel lCoureur3_4;
    private javax.swing.JLabel lCoureur4_1;
    private javax.swing.JLabel lCoureur4_2;
    private javax.swing.JLabel lCoureur4_3;
    private javax.swing.JLabel lCoureur4_4;
    private javax.swing.JLabel lEquipe1;
    private javax.swing.JLabel lEquipe2;
    private javax.swing.JLabel lEquipe3;
    private javax.swing.JLabel lEquipe4;
    private javax.swing.JLabel lTitreListe;
    private javax.swing.JList liste;
    private javax.swing.JPanel panelEquipe1;
    private javax.swing.JPanel panelEquipe2;
    private javax.swing.JPanel panelEquipe3;
    private javax.swing.JPanel panelEquipe4;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JProgressBar pbCoureur1_1;
    private javax.swing.JProgressBar pbCoureur1_2;
    private javax.swing.JProgressBar pbCoureur1_3;
    private javax.swing.JProgressBar pbCoureur1_4;
    private javax.swing.JProgressBar pbCoureur2_1;
    private javax.swing.JProgressBar pbCoureur2_2;
    private javax.swing.JProgressBar pbCoureur2_3;
    private javax.swing.JProgressBar pbCoureur2_4;
    private javax.swing.JProgressBar pbCoureur3_1;
    private javax.swing.JProgressBar pbCoureur3_2;
    private javax.swing.JProgressBar pbCoureur3_3;
    private javax.swing.JProgressBar pbCoureur3_4;
    private javax.swing.JProgressBar pbCoureur4_1;
    private javax.swing.JProgressBar pbCoureur4_2;
    private javax.swing.JProgressBar pbCoureur4_3;
    private javax.swing.JProgressBar pbCoureur4_4;
    private javax.swing.JTextField tChrono;
    private javax.swing.JTextField tHorloge;
    // End of variables declaration//GEN-END:variables
    private ItfCtrlIhm refCtrl;
    private DefaultListModel model;
}
